/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-29-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   06-29-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public class EmployeeUtilTest {
  
  static testMethod void empTestMethod(){
    EmployeeUtil e = new EmployeeUtil();
    EmployeeUtil.getEmployee();
    EmployeeUtil.finalCommit();
    EmployeeUtil.getGit();
   }
}
